// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: sdata.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApName      *string `protobuf:"bytes,1,req,name=ap_name,json=apName" json:"ap_name,omitempty"`
	SensorId    *int32  `protobuf:"varint,2,opt,name=sensor_id,json=sensorId" json:"sensor_id,omitempty"`
	SensorValue *int32  `protobuf:"zigzag32,3,opt,name=sensor_value,json=sensorValue" json:"sensor_value,omitempty"`
	Status      *int32  `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_sdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_sdata_proto_rawDescGZIP(), []int{0}
}

func (x *SensorData) GetApName() string {
	if x != nil && x.ApName != nil {
		return *x.ApName
	}
	return ""
}

func (x *SensorData) GetSensorId() int32 {
	if x != nil && x.SensorId != nil {
		return *x.SensorId
	}
	return 0
}

func (x *SensorData) GetSensorValue() int32 {
	if x != nil && x.SensorValue != nil {
		return *x.SensorValue
	}
	return 0
}

func (x *SensorData) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

var File_sdata_proto protoreflect.FileDescriptor

var file_sdata_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x61, 0x69, 0x6e, 0x22, 0x7d, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x11, 0x52, 0x0b, 0x73,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73,
}

var (
	file_sdata_proto_rawDescOnce sync.Once
	file_sdata_proto_rawDescData = file_sdata_proto_rawDesc
)

func file_sdata_proto_rawDescGZIP() []byte {
	file_sdata_proto_rawDescOnce.Do(func() {
		file_sdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdata_proto_rawDescData)
	})
	return file_sdata_proto_rawDescData
}

var file_sdata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdata_proto_goTypes = []interface{}{
	(*SensorData)(nil), // 0: main.SensorData
}
var file_sdata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdata_proto_init() }
func file_sdata_proto_init() {
	if File_sdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdata_proto_goTypes,
		DependencyIndexes: file_sdata_proto_depIdxs,
		MessageInfos:      file_sdata_proto_msgTypes,
	}.Build()
	File_sdata_proto = out.File
	file_sdata_proto_rawDesc = nil
	file_sdata_proto_goTypes = nil
	file_sdata_proto_depIdxs = nil
}
